### PR TITLE
Add some flavor

### PR DESCRIPTION
**Pull request by onbjerg**
Guy Fieri

### CODE REVIEW

**Comment by ikkerens** [comment]
You do realize this increases the filesize of the framework with 9333.18%?

**Comment by onbjerg** [comment]
Flavorville

**Comment by Stenkilde** [comment]
https://media.giphy.com/media/yf9VXSADz8GlO/giphy.gif

**Comment by olidotjpeg** [comment]
Flavorville

**Comment by kaspergrubbe** [comment]
:8ball:

**Pull request closed without merging**
