### PR TITLE
Ignore `node_modules`

### PR DESCRIPTION
**Pull request by onbjerg**
Someone might be stupid enough to commit them (read: me)

### CODE REVIEW

**Comment by olidotjpeg** [comment]
This is very important and we should investigate how to properly implement this @kaspergrubbe

**Comment by onbjerg** [comment]
Not sure if it should be `/node_modules` or `node_modules` or `node_modules/` or `/node_modules/`. Any help is greatly appreciated!

**Comment by YOzaz** [comment]
Any of them will work, I'm using `/node_modules` or `/**/node_modules/` if it's intended to be in `public` folder.

**Comment by olidotjpeg** [comment]
/*/ ?

**Comment by YOzaz** [comment]
With version 1.8.2 of git, you can also use the *\* wildcard to match any level of subdirectories.
https://git-scm.com/docs/gitignore

**Pull request merged**
