### PR TITLE
File size optimization

### PR DESCRIPTION
**Pull request by ikkerens**
In working with this Framework I have found that the framework could use some optimizations.
Sadly this change does require the short tags functionality enabled of PHP, but I figured it'd be worth posting nonetheless.

In this change, I have managed to reduce the filesize of the framework by 12%, effectively decreasing the parsing time required. Most developers will see a notable performance increase when benchmarking this >1.000.000 times.

### CODE REVIEW

**Comment by kaspergrubbe** [comment]
This simply sounds too good to be true, and I trust your very extensive research and benchmarks. I mean, who can argue against an incredible 12% improvement?

**Comment by YOzaz** [comment]
I would argue that this optimization is worth the restrictions we'll face. Short tag syntax has to be explicitly enabled through `short_open_tag` setting, which is a problem on shared hosting platforms.

**Comment by C0DK** [comment]
i'd argue that you should make two different versions. one for short_open_tag and one without. Make the framework more vertile.

**Comment by YOzaz** [comment]
From the other hand, if we want to make it **fastest**...

**Comment by olidotjpeg** [comment]
Honestly, if people are running without `short_open_tag` they should just stop using this badass framework

**Comment by YOzaz** [comment]
@Stenkilde good point.

**Comment by Steiniche** [comment]
I welcome this change and we can't argue with a staggering 12% improvement!

**Pull request merged**
